name: build
on: [push]
jobs:
  build-windows-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake --build .
  build-windows-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake --build . --config Release